server:
  port: 8010
spring:
  application:
    name: microservice.order.service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msorder?createDatabaseIfNotExist=true&useUnicode=true&autoReconnect=true
    username: msecom
    password: msecom
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: root
    password: dillon
  cloud:
    stream:
      bindings:
        inboundProductChanges:
          destination: prodChangeTopic
          content-type: application/json
          group: orderGroup
  cache:
    type: REDIS
  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: 192.168.99.100  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    timeout: 2000       # 连接超时时间（毫秒）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0    # 连接池中的最小空闲连接
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.sleuth: DEBUG
    com.bdtv.ms: DEBUG
security:
  oauth2:
    resource:
      id: microservice.order.service
      userInfoUri: http://localhost:8902/microservice.auth.service/user
      preferTokenInfo: false
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health, refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: container
server:
  port: 8202
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/

---
spring:
  profiles: container
  jpa:
    show-sql: true
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
