encrypt:
  key: dillonzhang
server:
  port: 9090
spring:
  application:
    name: microservice.config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dillonzhang/spring-cloud-config-repo
          search-paths: order,product
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true