server:
  port: 8001
spring:
  application:
    name: microservice.product.service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msproduct?createDatabaseIfNotExist=true&useUnicode=true&autoReconnect=true
    username: msecom
    password: msecom
    initialize: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: root
    password: dillon
  cloud:
    stream:
      bindings:
        output:
          destination: prodChangeTopic
          content-type: application/json
security:
  oauth2:
    resource:
      id: microservice.product.service
      userInfoUri: http://localhost:8902/microservice.auth.service/user
      preferTokenInfo: false
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.bdtv.ms.ecom.product.service.controller: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

mockEnabled: false

